const ADD_TRANSACTIONS = 'ADD_TRANSACTIONS';
const CHECK_BALANCE = 'CHECK_BALANCE';
const DEPOSIT = 'DEPOSIT';
const FETCH_BALANCE = 'FETCH_BALANCE';
const RECEIVE_DATA = 'RECEIVE_DATA';
const RECEIVE_DONE = 'RECEIVE_DONE';
const RECEIVE_ERROR = 'RECEIVE_ERROR';
const UPDATE_BALANCE = 'UPDATE_BALANCE';
const WITHDRAW = 'WITHDRAW';

export { ADD_TRANSACTIONS, CHECK_BALANCE, DEPOSIT, FETCH_BALANCE, RECEIVE_DATA,
	RECEIVE_DONE, RECEIVE_ERROR, UPDATE_BALANCE, WITHDRAW };